# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 10.202.22.46
  port: 32200
  role:
  - controlplane
  - worker
  - etcd
  user: zhangbin05
  ssh_key_path: /home/zhangbin05/id_rsa
- address: 10.202.22.47
  port: 32200
  role:
  - controlplane
  - worker
  - etcd
  user: zhangbin05
  ssh_key_path: /home/zhangbin05/id_rsa
- address: 10.202.22.48
  port: 32200
  role:
  - controlplane
  - worker
  - etcd
  user: zhangbin05
  ssh_key_path: /home/zhangbin05/id_rsa
- address: 10.202.22.49
  port: 32200
  role:
  - worker
  user: zhangbin05
  ssh_key_path: /home/zhangbin05/id_rsa
services:
  etcd:
    snapshot: true
    creation: 12h
    retention: 24h
  kube-api:
    extra_args:
      # Enable audit log to stdout
      audit-log-path: "-"
      # Increase number of delete workers
      delete-collection-workers: 3
      # Set the level of log output to debug-level
      v: 4
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: 1-65353
    pod_security_policy: false
    always_pull_images: false
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  kubelet:
    extra_args:
      max-pods: 250
      feature-gates: KubeletPodResources=true
    extra_binds:
      - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
network:
  plugin: canal
  options:
    canal_iface: eth0
    canal_flannel_backend_type: vxlan
authentication:
  strategy: x509
system_images:
  etcd: rancher-kube/coreos-etcd:v3.4.3-rancher1
  alpine: rancher-kube/rke-tools:v0.1.52
  nginx_proxy: rancher-kube/rke-tools:v0.1.52
  cert_downloader: rancher-kube/rke-tools:v0.1.52
  kubernetes_services_sidecar: rancher-kube/rke-tools:v0.1.52
  kubedns: rancher-kube/k8s-dns-kube-dns:1.15.0
  dnsmasq: rancher-kube/k8s-dns-dnsmasq-nanny:1.15.0
  kubedns_sidecar: rancher-kube/k8s-dns-sidecar:1.15.0
  kubedns_autoscaler: rancher-kube/cluster-proportional-autoscaler:1.7.1
  coredns: rancher-kube/coredns-coredns:1.6.5
  coredns_autoscaler: rancher-kube/cluster-proportional-autoscaler:1.7.1
  kubernetes: rancher-kube/hyperkube:v1.17.2-rancher1
  flannel: rancher-kube/coreos-flannel:v0.11.0-rancher1
  flannel_cni: rancher-kube/flannel-cni:v0.3.0-rancher5
  calico_node: rancher-kube/calico-node:v3.10.2
  calico_cni: rancher-kube/calico-cni:v3.10.2
  calico_controllers: rancher-kube/calico-kube-controllers:v3.10.2
  calico_ctl: rancher-kube/calico-ctl:v2.0.0
  calico_flexvol: rancher-kube/calico-pod2daemon-flexvol:v3.10.2
  canal_node: rancher-kube/calico-node:v3.10.2
  canal_cni: rancher-kube/calico-cni:v3.10.2
  canal_flannel: rancher-kube/coreos-flannel:v0.11.0
  canal_flexvol: rancher-kube/calico-pod2daemon-flexvol:v3.10.2
  weave_node: rancher-kube/weave-kube:2.5.2
  weave_cni: rancher-kube/weave-npc:2.5.2
  pod_infra_container: rancher-kube/pause:3.1
  ingress: rancher-kube/nginx-ingress-controller:nginx-0.25.1-rancher1
  ingress_backend: rancher-kube/nginx-ingress-controller-defaultbackend:1.5-rancher1
  metrics_server: rancher-kube/metrics-server:v0.3.6
  windows_pod_infra_container: rancher-kube/kubelet-pause:v0.1.3
ssh_key_path: /home/zhangbin05/id_rsa
ssh_agent_auth: false
authorization:
  mode: rbac
ignore_docker_version: true
kubernetes_version: "v1.17.2-rancher1-2"
private_registries: 
- url: registry.cn-shenzhen.aliyuncs.com
  user: lzywbh1993
  password: *west
  is_default: true
ingress:
  provider: nginx
  node_selector:
    app: ingress
cluster_name: "ai-demo"
dns:
  provider: coredns
addon_job_timeout: 30
